import type { SandboxContainmentConfig, SandboxHarnessId } from "./seatbelt-config.js";
import { resolvedAllowedPaths, resolvedDeniedPaths } from "./seatbelt-config.js";
import { seatbeltSubpathLiteral } from "./seatbelt-paths.js";

/** Minimal exec profile when no containment config exists (network denied). */
export const SEATBELT_EXEC_PROFILE_V1 = `(version 1)
(allow default)
(deny network*)
`;

/**
 * Parameterized harness profile — blocks file-write outside WORK_DIR, CLAWQL_DIR, /tmp,
 * and configured allowed roots. Sensitive paths denied via params + config.
 *
 * Invoke: sandbox-exec -f {harness}.sb -D WORK_DIR=... -D CLAWQL_DIR=... ...
 */
export function buildHarnessSeatbeltProfile(
  config: SandboxContainmentConfig,
  harness: SandboxHarnessId
): string {
  const allowed = resolvedAllowedPaths(config);
  const denied = resolvedDeniedPaths(config);

  const extraWriteAllows = allowed
    .map((p) => `(allow file-write* (subpath "${seatbeltSubpathLiteral(p)}"))`)
    .join("\n");

  const extraDenyRead = denied
    .map((p) => `(deny file-read* (subpath "${seatbeltSubpathLiteral(p)}"))`)
    .join("\n");

  const extraDenyWrite = denied
    .map((p) => `(deny file-write* (subpath "${seatbeltSubpathLiteral(p)}"))`)
    .join("\n");

  return `; ClawQL harness profile: ${harness}
; Generated by clawql sandbox init — customize via clawql sandbox edit --harness ${harness}
(version 1)
(allow default)
(deny file-write*)
(allow file-write*
  (subpath "/tmp")
  (subpath "/private/tmp")
  (subpath (param "WORK_DIR"))
  (subpath (param "CLAWQL_DIR")))
${extraWriteAllows}
(deny file-read*
  (subpath (param "HOME_SSH"))
  (subpath (param "HOME_AWS"))
  (subpath (param "HOME_CONFIG")))
${extraDenyRead}
${extraDenyWrite}
(deny network*)
`;
}

/** @deprecated Use buildHarnessSeatbeltProfile */
export function buildAgentSeatbeltProfile(
  config: SandboxContainmentConfig
): string {
  return buildHarnessSeatbeltProfile(config, "claude");
}

/**
 * sandbox_exec profile — parameterized workspace + allowed roots; network denied.
 */
export function buildExecSeatbeltProfile(
  config: SandboxContainmentConfig,
  workspaceRoot: string
): string {
  const allowed = resolvedAllowedPaths(config);
  const denied = resolvedDeniedPaths(config);

  const extraWriteAllows = allowed
    .map((p) => `(allow file-write* (subpath "${seatbeltSubpathLiteral(p)}"))`)
    .join("\n");

  const extraDeny = denied
    .flatMap((p) => [
      `(deny file-read* (subpath "${seatbeltSubpathLiteral(p)}"))`,
      `(deny file-write* (subpath "${seatbeltSubpathLiteral(p)}"))`,
    ])
    .join("\n");

  return `; ClawQL sandbox_exec profile
(version 1)
(allow default)
(deny file-write*)
(allow file-write*
  (subpath "/tmp")
  (subpath "/private/tmp")
  (subpath (param "WORK_DIR"))
  (subpath (param "CLAWQL_DIR"))
  (subpath "${seatbeltSubpathLiteral(workspaceRoot)}"))
(allow file-read*
  (subpath "${seatbeltSubpathLiteral(workspaceRoot)}"))
${extraWriteAllows}
(deny file-read*
  (subpath (param "HOME_SSH"))
  (subpath (param "HOME_AWS"))
  (subpath (param "HOME_CONFIG")))
${extraDeny}
(deny network*)
`;
}

/** Build sandbox-exec argv: -f profile -D KEY=val ... -- command args */
export function sandboxExecArgv(
  profilePath: string,
  params: Record<string, string>,
  command: string,
  args: string[] = []
): string[] {
  const out: string[] = ["-f", profilePath];
  for (const [key, value] of Object.entries(params)) {
    out.push("-D", `${key}=${value}`);
  }
  out.push("--", command, ...args);
  return out;
}
