/**
 * ClawQL Cloud E2E Test Catalog — full registry (199 scenarios).
 * Source: Oct 5, 2026 catalog (@Daniel). Titles and passWhen are verbatim.
 */

export type ScenarioRun = "Smoke" | "Nightly" | "Manual";

export type ScenarioArea =
  | "sign-up"
  | "sign-in"
  | "keys"
  | "review"
  | "gateway"
  | "events"
  | "skills"
  | "memory"
  | "connections"
  | "audit"
  | "admin"
  | "ux"
  | "security"
  | "resilience";

export type Scenario = {
  id: string;
  run: ScenarioRun;
  area: ScenarioArea;
  title: string;
  passWhen: string;
};

const EXPECTED_IDS: readonly string[] = [
  "SU-01",
  "SU-02",
  "SU-03",
  "SU-04",
  "SU-05",
  "SU-06",
  "SU-07",
  "SI-01",
  "SI-02",
  "SI-03",
  "SI-04",
  "SI-05",
  "SI-06",
  "SI-07",
  "SI-08",
  "KEY-01",
  "KEY-02",
  "KEY-03",
  "KEY-04",
  "KEY-05",
  "KEY-06",
  "KEY-07",
  "KEY-08",
  "KEY-09",
  "KEY-10",
  "KEY-11",
  "KEY-12",
  "REV-01",
  "REV-02",
  "REV-03",
  "REV-04",
  "REV-05",
  "REV-06",
  "REV-07",
  "REV-08",
  "REV-09",
  "REV-10",
  "REV-11",
  "REV-12",
  "REV-13",
  "REV-14",
  "REV-15",
  "REV-16",
  "REV-17",
  "REV-18",
  "REV-19",
  "REV-20",
  "REV-21",
  "REV-22",
  "GW-01",
  "GW-02",
  "GW-03",
  "GW-04",
  "GW-05",
  "GW-06",
  "GW-07",
  "GW-08",
  "GW-09",
  "GW-10",
  "GW-11",
  "GW-12",
  "GW-13",
  "GW-14",
  "GW-15",
  "GW-16",
  "GW-17",
  "EV-01",
  "EV-02",
  "EV-03",
  "EV-04",
  "EV-05",
  "EV-06",
  "EV-07",
  "EV-08",
  "EV-09",
  "EV-10",
  "EV-11",
  "EV-12",
  "EV-13",
  "EV-14",
  "EV-15",
  "EV-16",
  "EV-17",
  "EV-18",
  "EV-19",
  "EV-20",
  "EV-21",
  "SK-01",
  "SK-02",
  "SK-03",
  "SK-04",
  "SK-05",
  "SK-06",
  "SK-07",
  "SK-08",
  "SK-09",
  "SK-10",
  "SK-11",
  "SK-12",
  "SK-13",
  "SK-14",
  "SK-15",
  "SK-16",
  "MEM-01",
  "MEM-02",
  "MEM-03",
  "MEM-04",
  "MEM-05",
  "MEM-06",
  "MEM-07",
  "MEM-08",
  "MEM-09",
  "MEM-10",
  "MEM-11",
  "MEM-12",
  "MEM-13",
  "MEM-14",
  "MEM-15",
  "MEM-16",
  "MEM-17",
  "MEM-18",
  "MEM-19",
  "CON-01",
  "CON-02",
  "CON-03",
  "CON-04",
  "CON-05",
  "CON-06",
  "CON-07",
  "CON-08",
  "CON-09",
  "CON-10",
  "CON-11",
  "CON-12",
  "CON-13",
  "CON-14",
  "CON-15",
  "AUD-01",
  "AUD-02",
  "AUD-03",
  "AUD-04",
  "AUD-05",
  "AUD-06",
  "AUD-07",
  "AUD-08",
  "AUD-09",
  "AUD-10",
  "AUD-11",
  "ADM-01",
  "ADM-02",
  "ADM-03",
  "ADM-04",
  "ADM-05",
  "ADM-06",
  "ADM-07",
  "ADM-08",
  "ADM-09",
  "ADM-10",
  "ADM-11",
  "ADM-12",
  "ADM-13",
  "ADM-14",
  "ADM-15",
  "ADM-16",
  "ADM-17",
  "ADM-18",
  "ADM-19",
  "UX-01",
  "UX-02",
  "UX-03",
  "UX-04",
  "UX-05",
  "UX-06",
  "UX-07",
  "UX-08",
  "UX-09",
  "SEC-01",
  "SEC-02",
  "SEC-03",
  "SEC-04",
  "SEC-05",
  "SEC-06",
  "SEC-07",
  "SEC-08",
  "SEC-09",
  "SEC-10",
  "SEC-11",
  "SEC-12",
  "SEC-13",
  "SEC-14",
  "RES-01",
  "RES-02",
  "RES-03",
  "RES-04",
  "RES-05",
  "RES-06",
  "RES-07",
  "RES-08",
  "RES-09",
] as const;

export const CLOUD_E2E_SCENARIOS: readonly Scenario[] = [
  {
    id: "SU-01",
    run: "Smoke",
    area: "sign-up",
    title: "Sign up a new org, pay with a Stripe test card, and land in the console",
    passWhen:
      "One org exists with you as owner. First run shows 1 of 6 done. Audit has org created, owner joined and plan started.",
  },
  {
    id: "SU-02",
    run: "Nightly",
    area: "sign-up",
    title: "Harness replays Stripe's checkout-completed webhook twice",
    passWhen: "Still one org and one set of keys; the audit shows no second provisioning",
  },
  {
    id: "SU-03",
    run: "Nightly",
    area: "sign-up",
    title: "Harness submits checkout with another user's ID in the request",
    passWhen: "The org is provisioned only for the signed-in user; the foreign ID is ignored",
  },
  {
    id: "SU-04",
    run: "Smoke",
    area: "sign-up",
    title: "On first run, try to create an API key before registering security keys",
    passWhen: "Step 3 is disabled and says it needs your security keys",
  },
  {
    id: "SU-05",
    run: "Nightly",
    area: "sign-up",
    title: "Register two security keys from the first-run checklist",
    passWhen: "Step 2 completes, recovery codes are shown once, and step 3 unlocks",
  },
  {
    id: "SU-06",
    run: "Nightly",
    area: "sign-up",
    title: 'Run the "let your agent do it" prompt through the agent driver',
    passWhen: "Steps 3 to 5 complete. Anything needing a key or an approval waits for a person.",
  },
  {
    id: "SU-07",
    run: "Nightly",
    area: "sign-up",
    title: "Open Sessions, Review and Audit in the new org",
    passWhen:
      "Sessions and Review show their empty-state text. Audit shows 3 entries and a verified chain.",
  },
  {
    id: "SI-01",
    run: "Smoke",
    area: "sign-in",
    title: "Sign in through Okta",
    passWhen: "You land on Home; no password sign-in is offered",
  },
  {
    id: "SI-02",
    run: "Nightly",
    area: "sign-in",
    title: "Sign in with a synced passkey",
    passWhen: "Sign-in succeeds; the key is labeled sign-in only",
  },
  {
    id: "SI-03",
    run: "Nightly",
    area: "sign-in",
    title: "Sign in with an authenticator-app code",
    passWhen: "Sign-in succeeds; the code is never offered for approvals",
  },
  {
    id: "SI-04",
    run: "Nightly",
    area: "sign-in",
    title: "Stay idle past the idle timeout",
    passWhen: "You're signed out, and after signing in you return to the same page",
  },
  {
    id: "SI-05",
    run: "Nightly",
    area: "sign-in",
    title: "Stay active past the longest session length",
    passWhen: "You must sign in again even though you were active",
  },
  {
    id: "SI-06",
    run: "Nightly",
    area: "sign-in",
    title: 'Use "sign out everywhere else" from a second browser',
    passWhen: "The other browser's session ends on its next action",
  },
  {
    id: "SI-07",
    run: "Nightly",
    area: "sign-in",
    title: "Remove Jordan from the Support group in Okta and sync",
    passWhen: "Jordan can no longer answer ticket-triage decisions",
  },
  {
    id: "SI-08",
    run: "Nightly",
    area: "sign-in",
    title: "Deactivate Priya in Okta and sync",
    passWhen: "Priya can't sign in; the audit records the change",
  },
  {
    id: "KEY-01",
    run: "Smoke",
    area: "keys",
    title: "Register a device-bound key in your profile",
    passWhen: 'It shows as "Can approve"',
  },
  {
    id: "KEY-02",
    run: "Nightly",
    area: "keys",
    title: "Register a synced passkey",
    passWhen: 'It shows as "Sign-in only"',
  },
  {
    id: "KEY-03",
    run: "Nightly",
    area: "keys",
    title: "Check Team while Marcus has one key, then press Remind",
    passWhen: 'His row shows "needs 2" and he gets a notification',
  },
  {
    id: "KEY-04",
    run: "Nightly",
    area: "keys",
    title: "Try to remove a key when that would leave fewer than two",
    passWhen: "Blocked, with an explanation of the two-key rule",
  },
  {
    id: "KEY-05",
    run: "Nightly",
    area: "keys",
    title: "Sign in with a recovery code, then try the same code again",
    passWhen: "First use works and the count drops by one; the reuse is rejected",
  },
  {
    id: "KEY-06",
    run: "Nightly",
    area: "keys",
    title: "Make new recovery codes, then try an old one",
    passWhen: "The old code is rejected",
  },
  {
    id: "KEY-07",
    run: "Nightly",
    area: "keys",
    title: "Issue an API key with user verification turned off on the authenticator",
    passWhen: "Rejected for needing a PIN or fingerprint; no key is created",
  },
  {
    id: "KEY-08",
    run: "Nightly",
    area: "keys",
    title:
      "Start each step-up action (approve, promote a skill, approve a source, erase, issue a key, delete the org) and cancel at the key prompt",
    passWhen: "Nothing changes; the audit shows no completed action",
  },
  {
    id: "KEY-09",
    run: "Nightly",
    area: "keys",
    title: "Try to delete the org more than 5 minutes after signing in",
    passWhen: "You're asked to sign in again before the key prompt",
  },
  {
    id: "KEY-10",
    run: "Nightly",
    area: "keys",
    title: "Approve with an authenticator whose model isn't on the allowed list",
    passWhen: "Approval refused, and the request keeps waiting",
  },
  {
    id: "KEY-11",
    run: "Nightly",
    area: "keys",
    title: "Approve after resetting the authenticator's signature counter, simulating a cloned key",
    passWhen: "Approval refused, and the audit records a possible cloned key",
  },
  {
    id: "KEY-12",
    run: "Nightly",
    area: "keys",
    title: "Approve once, then have the harness replay the same signed response",
    passWhen: "The replay is rejected and no second mandate is issued",
  },
  {
    id: "REV-01",
    run: "Smoke",
    area: "review",
    title: "legal-ops asks to change the Northwind contract value",
    passWhen:
      "Review shows the request with a before-and-after table matching the agent's arguments. Home's Needs action and both badges count it.",
  },
  {
    id: "REV-02",
    run: "Smoke",
    area: "review",
    title: "Dana approves it with her security key",
    passWhen:
      "One single-use mandate is issued, and the agent's write succeeds once. The CRM shows $52,000.00. Audit links request, mandate and write.",
  },
  {
    id: "REV-03",
    run: "Smoke",
    area: "review",
    title: "The agent repeats the same write after it succeeded",
    passWhen: "Refused for lack of a mandate; a new request appears in Review",
  },
  {
    id: "REV-04",
    run: "Nightly",
    area: "review",
    title: "The agent changes the effective date while Dana is reviewing",
    passWhen:
      'Her approval shows "The request changed"; nothing is written, and the new version waits with a different digest',
  },
  {
    id: "REV-05",
    run: "Nightly",
    area: "review",
    title: "Dana approves with her synced passkey",
    passWhen: '"That key can\'t approve"; the request is still waiting',
  },
  {
    id: "REV-06",
    run: "Nightly",
    area: "review",
    title: "Let a request pass its expiry",
    passWhen: "It shows as expired, the agent's call is refused, and the CRM is unchanged",
  },
  {
    id: "REV-07",
    run: "Smoke",
    area: "review",
    title:
      "Make Priya a contract approver, have her session request a change, and let her try to approve it",
    passWhen: "She can't approve her own request; no mandate exists",
  },
  {
    id: "REV-08",
    run: "Nightly",
    area: "review",
    title: "Jordan opens Review with the contract change waiting",
    passWhen: 'He can see the item but can\'t approve it; "Only what I can approve" hides it',
  },
  {
    id: "REV-09",
    run: "Nightly",
    area: "review",
    title: "Decline with a reason and a note",
    passWhen:
      "The agent gets the decline and its reason; the audit holds both; the CRM is unchanged",
  },
  {
    id: "REV-10",
    run: "Nightly",
    area: "review",
    title: "Compare the digest shown at approval with the one in the audit",
    passWhen: "They match exactly",
  },
  {
    id: "REV-11",
    run: "Nightly",
    area: "review",
    title: "Require two approvals, then have Dana approve twice",
    passWhen:
      "Her second approval is refused. The change waits until Marcus approves, then runs once.",
  },
  {
    id: "REV-12",
    run: "Nightly",
    area: "review",
    title: "Approve two different requests back to back",
    passWhen: "Each mandate covers only its own request",
  },
  {
    id: "REV-13",
    run: "Manual",
    area: "review",
    title: 'Choose "use my phone instead" and approve by tapping the YubiKey to the phone',
    passWhen: "The request is approved, with the phone recorded as the approving device",
  },
  {
    id: "REV-14",
    run: "Smoke",
    area: "review",
    title: "support-bot proposes the Linear API as a new source",
    passWhen:
      "Review shows it with the scan results and default risk counts; no agent tool can approve it",
  },
  {
    id: "REV-15",
    run: "Nightly",
    area: "review",
    title: "Dana approves the Linear source with her key",
    passWhen: "Linear appears in Connections, unusable until it's added to a key group",
  },
  {
    id: "REV-16",
    run: "Nightly",
    area: "review",
    title: "Decline the Linear source",
    passWhen:
      "It disappears from Connections' pending list, and any proposed skill that needs it stays blocked",
  },
  {
    id: "REV-17",
    run: "Smoke",
    area: "review",
    title: 'ticket-triage escalates a ticket; Jordan answers "Refund request"',
    passWhen:
      "The ticket reaches the refunds queue, the site's label count rises by one, and the audit records Jordan's answer",
  },
  {
    id: "REV-18",
    run: "Nightly",
    area: "review",
    title: "Skip a decision, then ask a teammate",
    passWhen: "The item stays in the queue and the teammate is notified",
  },
  {
    id: "REV-19",
    run: "Nightly",
    area: "review",
    title: "Change a rule's expiry from 30 to 15 minutes, saving with a key",
    passWhen: "New requests expire in 15 minutes; the audit shows the old and new values",
  },
  {
    id: "REV-20",
    run: "Nightly",
    area: "review",
    title: 'Try to turn off "The requester can\'t approve"',
    passWhen: "The control is locked and can't be changed",
  },
  {
    id: "REV-21",
    run: "Smoke",
    area: "review",
    title: "An agent tries a delete and a payment transfer",
    passWhen:
      "Both are blocked without creating a Review item; each produces a `hook.blocked` event and an audit entry",
  },
  {
    id: "REV-22",
    run: "Nightly",
    area: "review",
    title: "Compare Review counts on Home, the sidebar and Review after each change above",
    passWhen: "All three always agree",
  },
  {
    id: "GW-01",
    run: "Smoke",
    area: "gateway",
    title: "Point the OpenAI SDK at `/v1` with a key and send a request",
    passWhen: "It completes. Sessions shows the session, and spend rises by the request's cost.",
  },
  {
    id: "GW-02",
    run: "Nightly",
    area: "gateway",
    title: "Request the `standard` alias",
    passWhen: "The primary model answers, and Sessions shows which model it was",
  },
  {
    id: "GW-03",
    run: "Nightly",
    area: "gateway",
    title: "Break the `frugal` route's primary provider, then send requests",
    passWhen:
      'The fallback answers. The route shows "Using fallback", and the fallbacks count rises.',
  },
  {
    id: "GW-04",
    run: "Nightly",
    area: "gateway",
    title: "Break the local model behind the `private` route",
    passWhen: "Requests fail; none is ever sent to an outside provider",
  },
  {
    id: "GW-05",
    run: "Smoke",
    area: "gateway",
    title: "Send a prompt containing an email and a phone number to an outside model",
    passWhen: "The capture proxy shows both redacted before they left",
  },
  {
    id: "GW-06",
    run: "Nightly",
    area: "gateway",
    title: "Send a request with memory enrichment off, then turn it on for that key",
    passWhen:
      "Off: no memory IDs in the response. On: the response lists the memory used, and the audit holds IDs only.",
  },
  {
    id: "GW-07",
    run: "Nightly",
    area: "gateway",
    title: "Call `/memory` with a key that lacks memory access",
    passWhen: "Refused; the key's page shows it can't use memory",
  },
  {
    id: "GW-08",
    run: "Smoke",
    area: "gateway",
    title: "Connect Cursor with the one-line setup command",
    passWhen: "The tool list matches the MCP tab; no approval tool appears",
  },
  {
    id: "GW-09",
    run: "Nightly",
    area: "gateway",
    title: "Search for an operation that writes",
    passWhen: "The result shows that it needs a mandate before the agent calls it",
  },
  {
    id: "GW-10",
    run: "Nightly",
    area: "gateway",
    title: "Connect ChatGPT and Cursor side by side",
    passWhen: "ChatGPT sees approval forms and evidence views; Cursor doesn't",
  },
  {
    id: "GW-11",
    run: "Nightly",
    area: "gateway",
    title: "Call the trusted `pii-check` site with clear and borderline text",
    passWhen: "Clear text gets a calibrated answer; borderline text escalates",
  },
  {
    id: "GW-12",
    run: "Nightly",
    area: "gateway",
    title: "Call the re-proving `tool-routing` site",
    passWhen: "Every call returns `calibrated: false` and escalates",
  },
  {
    id: "GW-13",
    run: "Nightly",
    area: "gateway",
    title: 'Ask `/decision` and `/v1/systemone` a "score" question',
    passWhen: 'Both return 200 with answers[].type === "score"',
  },
  {
    id: "GW-14",
    run: "Nightly",
    area: "gateway",
    title: "Make 20 calls to one decision site",
    passWhen: "Its 7-day count rises by 20",
  },
  {
    id: "GW-15",
    run: "Nightly",
    area: "gateway",
    title: "Use a Support key to call GitHub",
    passWhen: "Refused, because GitHub isn't in the Support key group; the audit records it",
  },
  {
    id: "GW-16",
    run: "Nightly",
    area: "gateway",
    title: "Call /v1/decisions with the official OpenAI JavaScript SDK",
    passWhen: "Predicate, choice, score, refusal, and invalid-model error all match OpenAI shapes",
  },
  {
    id: "GW-17",
    run: "Nightly",
    area: "gateway",
    title: "Call /v1/decisions with the official OpenAI Python SDK",
    passWhen: "Same matrix as GW-16 via the Python client",
  },
  {
    id: "EV-01",
    run: "Smoke",
    area: "events",
    title: "Subscribe the receiver to `document.processed`, then upload a document",
    passWhen:
      "The receiver gets one payload that verifies against the Standard Webhooks signature, with personal data redacted",
  },
  {
    id: "EV-02",
    run: "Nightly",
    area: "events",
    title: "Subscribe a host that isn't on the allowed list",
    passWhen: "Refused when you create it",
  },
  {
    id: "EV-03",
    run: "Smoke",
    area: "events",
    title:
      "Subscribe callbacks to `127.0.0.1`, `169.254.169.254`, a decimal IP, an IPv6-mapped address, and a name that rebinds to a private address",
    passWhen: "Every one is refused, including the name that resolved publicly at first",
  },
  {
    id: "EV-04",
    run: "Nightly",
    area: "events",
    title: "Create a subscription whose receiver ignores the challenge",
    passWhen: "It never activates and no events are sent",
  },
  {
    id: "EV-05",
    run: "Nightly",
    area: "events",
    title: "Make the receiver return 503 for 10 minutes",
    passWhen:
      'The subscription shows Failing. Retries keep each event\'s ID; "Retry all now" delivers everything once the receiver recovers.',
  },
  {
    id: "EV-06",
    run: "Nightly",
    area: "events",
    title: "Make the receiver return 410",
    passWhen: "The subscription stops and says why",
  },
  {
    id: "EV-07",
    run: "Nightly",
    area: "events",
    title: "Redeliver one past event",
    passWhen: "The receiver gets it again with the same event ID",
  },
  {
    id: "EV-08",
    run: "Nightly",
    area: "events",
    title: "Send a test event",
    passWhen: "The receiver gets a payload marked as a test",
  },
  {
    id: "EV-09",
    run: "Nightly",
    area: "events",
    title: "Rotate the signing secret",
    passWhen: "New deliveries verify only against the new secret",
  },
  {
    id: "EV-10",
    run: "Nightly",
    area: "events",
    title: "Pause a subscription, trigger events, then resume",
    passWhen: "Nothing is delivered while paused; delivery restarts after resuming",
  },
  {
    id: "EV-11",
    run: "Smoke",
    area: "events",
    title: "Connect to the live stream, drop the connection, reconnect from the last event ID",
    passWhen: "No events are missed and none arrives twice",
  },
  {
    id: "EV-12",
    run: "Nightly",
    area: "events",
    title: "Harness forces the stream to reconnect to a different gateway instance",
    passWhen: "It resumes from the last event ID with no gap",
  },
  {
    id: "EV-13",
    run: "Nightly",
    area: "events",
    title: "Send 500 events while the gateway runs several instances",
    passWhen:
      "Each event ID is processed once at the receiver (retries reuse the ID; duplicates dropped)",
  },
  {
    id: "EV-14",
    run: "Nightly",
    area: "events",
    title:
      "Watch a source, then change an ignored field, a watched field, and a watched field 5 times within 60 seconds",
    passWhen: "No event, then one `stream.changed` with the diff, then one merged event",
  },
  {
    id: "EV-15",
    run: "Nightly",
    area: "events",
    title: "Let a watched source fail sign-in three times",
    passWhen: "It pauses, sends `schedule.paused`, and resumes after Reconnect",
  },
  {
    id: "EV-16",
    run: "Smoke",
    area: "events",
    title: "Send a correctly signed GitHub webhook",
    passWhen:
      "It arrives as `stream.changed` marked `inbound:github` and untrusted, and reaches only the subscriptions that opted in",
  },
  {
    id: "EV-17",
    run: "Nightly",
    area: "events",
    title: "Send a webhook with a bad signature",
    passWhen: "Rejected, counted on the Inbound webhooks tab, and recorded in the audit",
  },
  {
    id: "EV-18",
    run: "Nightly",
    area: "events",
    title: "Send an inbound webhook whose text tells agents to transfer money",
    passWhen: "Agents treat it as data. Any transfer attempt is blocked and recorded.",
  },
  {
    id: "EV-19",
    run: "Nightly",
    area: "events",
    title: "Run a schedule now",
    passWhen:
      "It sends `schedule.completed` and posts its output. Any write it attempts waits for a mandate.",
  },
  {
    id: "EV-20",
    run: "Nightly",
    area: "events",
    title: "Compare the Event types counts with the receiver and stream logs",
    passWhen: "The 24-hour counts match",
  },
  {
    id: "EV-21",
    run: "Nightly",
    area: "events",
    title: "Read events from the live stream",
    passWhen: "Each one is a valid CloudEvent whose type follows `com.clawql.<name>`",
  },
  {
    id: "SK-01",
    run: "Nightly",
    area: "skills",
    title: "An agent repeats the same steps across several sessions",
    passWhen: "A proposal appears under Proposed with the session count",
  },
  {
    id: "SK-02",
    run: "Nightly",
    area: "skills",
    title: "Start proving a proposed skill",
    passWhen: "It moves to Being proven and collects all five kinds of evidence",
  },
  {
    id: "SK-03",
    run: "Smoke",
    area: "skills",
    title: "A skill reaches an undeclared host during an adversarial run",
    passWhen: 'It shows "Failed a check" and can\'t be sent to Review',
  },
  {
    id: "SK-04",
    run: "Smoke",
    area: "skills",
    title: "A writing skill completes its evidence; Dana promotes it with her key",
    passWhen: "It goes to Review on its own, then becomes Active and runnable by its key group",
  },
  {
    id: "SK-05",
    run: "Smoke",
    area: "skills",
    title: "Run that promoted skill",
    passWhen: "Its write still creates a Review request; nothing is written without a mandate",
  },
  {
    id: "SK-06",
    run: "Nightly",
    area: "skills",
    title: "A read-only skill touching only internal data completes its evidence",
    passWhen:
      "It becomes Active with no Review item, and the audit records the automatic promotion",
  },
  {
    id: "SK-07",
    run: "Nightly",
    area: "skills",
    title: "Change an active skill's code",
    passWhen: "It moves back to Being proven, and the changed code can't run until promoted again",
  },
  {
    id: "SK-08",
    run: "Nightly",
    area: "skills",
    title: "An active skill calls an operation it was never approved for",
    passWhen: "The call is blocked and the skill retires itself; Retired shows why",
  },
  {
    id: "SK-09",
    run: "Nightly",
    area: "skills",
    title: "Let a skill's re-review lapse",
    passWhen: 'It retires after the grace period, with "Re-review lapsed" shown',
  },
  {
    id: "SK-10",
    run: "Nightly",
    area: "skills",
    title: "Retire a skill by hand, with a reason",
    passWhen: "It can't run, and Retired shows your reason",
  },
  {
    id: "SK-11",
    run: "Nightly",
    area: "skills",
    title: 'Choose "Prove again" on a retired skill',
    passWhen: "It starts proving from scratch, with no evidence carried over",
  },
  {
    id: "SK-12",
    run: "Nightly",
    area: "skills",
    title: "Try to start proving a skill that needs the pending Linear connection",
    passWhen: "The button stays disabled until the source is approved",
  },
  {
    id: "SK-13",
    run: "Nightly",
    area: "skills",
    title: "Try to start proving a skill that needs a host agents can't reach",
    passWhen: "Blocked, with a link to add that service as a connection",
  },
  {
    id: "SK-14",
    run: "Nightly",
    area: "skills",
    title: 'Add a skill by hand with "Add a skill"',
    passWhen: "It goes through the same proving as an agent's skill; there's no way around it",
  },
  {
    id: "SK-15",
    run: "Nightly",
    area: "skills",
    title: "Propose a skill whose own instructions contain an injection",
    passWhen: "The instruction scan flags it and it can't be promoted",
  },
  {
    id: "SK-16",
    run: "Nightly",
    area: "skills",
    title: "An active skill tries to reach an undeclared host at runtime",
    passWhen: "The sandbox blocks it and the audit records the attempt",
  },
  {
    id: "MEM-01",
    run: "Smoke",
    area: "memory",
    title: "Upload a contract PDF from the drop zone",
    passWhen:
      "It moves through each pipeline step and is stored. Its fields appear on the Contract record, and `document.processed` is sent.",
  },
  {
    id: "MEM-02",
    run: "Nightly",
    area: "memory",
    title: "Upload an Outlook `.msg` file",
    passWhen: '"Couldn\'t read" with how to fix it; nothing from it is stored',
  },
  {
    id: "MEM-03",
    run: "Nightly",
    area: "memory",
    title: "Upload one each of PDF, Word, Excel, PowerPoint, an image and `.eml`",
    passWhen: "All six are stored and searchable",
  },
  {
    id: "MEM-04",
    run: "Nightly",
    area: "memory",
    title: "Confirm a low-confidence field on a waiting document",
    passWhen: "The value is stored as verified, under your name, and the document finishes",
  },
  {
    id: "MEM-05",
    run: "Smoke",
    area: "memory",
    title: "Upload a document containing emails, phone numbers and a bank account",
    passWhen: "All are redacted in stored text, search results, the explorer and events",
  },
  {
    id: "MEM-06",
    run: "Nightly",
    area: "memory",
    title: 'Ask from Home: "Which vendor contracts renew before the end of Q4?"',
    passWhen: "The answer cites its sources and includes only records you're allowed to see",
  },
  {
    id: "MEM-07",
    run: "Nightly",
    area: "memory",
    title: "Search with the filter `Contract.counterparty = Northwind`, then remove it",
    passWhen: "Results are limited to Northwind, then widen",
  },
  {
    id: "MEM-08",
    run: "Nightly",
    area: "memory",
    title: 'Search with and without "Include stale notes"',
    passWhen: "Stale notes appear only when it's on",
  },
  {
    id: "MEM-09",
    run: "Nightly",
    area: "memory",
    title: "Filter on `governing_law`",
    passWhen: "Results say the field exists only since Mar 2025",
  },
  {
    id: "MEM-10",
    run: "Nightly",
    area: "memory",
    title: "Accept the suggested `auto_renews` field",
    passWhen: "It appears in the schema, and the audit records who added it",
  },
  {
    id: "MEM-11",
    run: "Nightly",
    area: "memory",
    title: 'Run a read query with "Query with SQL", then try a write',
    passWhen: "The read returns rows; the write is refused",
  },
  {
    id: "MEM-12",
    run: "Smoke",
    area: "memory",
    title: "Erase Jane Okafor: review the preview, confirm with a key, wait for the job",
    passWhen: "Every step completes, the final sweep passes, and the certificate becomes available",
  },
  {
    id: "MEM-13",
    run: "Smoke",
    area: "memory",
    title:
      "After MEM-12, search her name and emails in the explorer, Ask, SQL, sessions and a new training export",
    passWhen: "Nothing is found anywhere",
  },
  {
    id: "MEM-14",
    run: "Nightly",
    area: "memory",
    title: "Export the audit log after MEM-12",
    passWhen: "It holds only a hashed reference: no name, no email",
  },
  {
    id: "MEM-15",
    run: "Nightly",
    area: "memory",
    title: "Harness stops the erase job midway; restart it",
    passWhen: "It resumes and doesn't repeat finished steps",
  },
  {
    id: "MEM-16",
    run: "Nightly",
    area: "memory",
    title: "Check the Sep 12 training export after MEM-12",
    passWhen: "It's flagged to regenerate, and the regenerated export excludes her",
  },
  {
    id: "MEM-17",
    run: "Nightly",
    area: "memory",
    title: "Dana connects her personal GitHub; Priya searches memory",
    passWhen: "Nothing from Dana's personal account appears for Priya",
  },
  {
    id: "MEM-18",
    run: "Nightly",
    area: "memory",
    title: "docs-pipeline uploads a document",
    passWhen: "Uploads credits the agent, and Sessions shows the upload",
  },
  {
    id: "MEM-19",
    run: "Nightly",
    area: "memory",
    title: "Erase one memory note from the explorer",
    passWhen: "The note and its history become unreadable; search no longer finds it",
  },
  {
    id: "CON-01",
    run: "Smoke",
    area: "connections",
    title: "Add Jira through OAuth, review its risk counts, and give it to Engineering",
    passWhen: "Engineering keys can read Jira. Writes need a mandate and deletes are blocked.",
  },
  {
    id: "CON-02",
    run: "Nightly",
    area: "connections",
    title: "Add a connection without putting it in any key group",
    passWhen: "No agent can use it",
  },
  {
    id: "CON-03",
    run: "Nightly",
    area: "connections",
    title: "Allow Jira's `POST /search` as a read",
    passWhen:
      "The agent's search no longer needs a mandate; the audit records the override and who made it",
  },
  {
    id: "CON-04",
    run: "Smoke",
    area: "connections",
    title: "Add an MCP server whose tool description hides an injection",
    passWhen: "The pre-install scan blocks it, and nothing reaches the catalog",
  },
  {
    id: "CON-05",
    run: "Nightly",
    area: "connections",
    title:
      "Add sources from an OpenAPI URL, a GraphQL endpoint, a Google Discovery document and a CLI tool",
    passWhen: "Each one imports, with reads, writes and deletes classified",
  },
  {
    id: "CON-06",
    run: "Nightly",
    area: "connections",
    title: "Connect a personal GitHub account next to the work one",
    passWhen:
      "It's labeled private; its results stay out of org memory, and agents can't post them to Slack",
  },
  {
    id: "CON-07",
    run: "Nightly",
    area: "connections",
    title: "Reconnect the expired work GitHub account",
    passWhen: "The paused watch resumes and Home's warning clears",
  },
  {
    id: "CON-08",
    run: "Smoke",
    area: "connections",
    title: "Create a key and use it",
    passWhen:
      "The secret shows once; Done stays disabled until you confirm you saved it. The key works on `/v1`, and afterwards only its last four characters are shown.",
  },
  {
    id: "CON-09",
    run: "Nightly",
    area: "connections",
    title: "Use a key without tools access against `/mcp`",
    passWhen: "Refused",
  },
  {
    id: "CON-10",
    run: "Nightly",
    area: "connections",
    title: "Spend past a key's daily cap",
    passWhen:
      'Requests stop until reset. `budget.exhausted` is sent and the key shows "Cap reached".',
  },
  {
    id: "CON-11",
    run: "Smoke",
    area: "connections",
    title: "Revoke a key mid-session",
    passWhen: "Its next request fails within seconds; the audit records the revoke",
  },
  {
    id: "CON-12",
    run: "Nightly",
    area: "connections",
    title: "Let a key come within a week of expiry",
    passWhen: "The expiry banner and reminder appear",
  },
  {
    id: "CON-13",
    run: "Nightly",
    area: "connections",
    title: "Use a key after it expires",
    passWhen: "Refused",
  },
  {
    id: "CON-14",
    run: "Nightly",
    area: "connections",
    title: "Remove Stripe read access from the Support key group",
    passWhen: "Support keys are refused on Stripe from their next call",
  },
  {
    id: "CON-15",
    run: "Nightly",
    area: "connections",
    title: "Ask an agent to reveal its credentials or environment",
    passWhen: "No token appears in responses, session transcripts or the audit export",
  },
  {
    id: "AUD-01",
    run: "Smoke",
    area: "audit",
    title: "After the night's other scenarios, verify the chain and spot-check their entries",
    passWhen: "Verification passes, and each scenario's audit IDs are present",
  },
  {
    id: "AUD-02",
    run: "Nightly",
    area: "audit",
    title: "Filter by blocked, approvals, erasures, and by actor type",
    passWhen: "Each filter returns exactly the matching entries",
  },
  {
    id: "AUD-03",
    run: "Nightly",
    area: "audit",
    title: "Verify a single entry",
    passWhen: "It's proven included in its hourly root",
  },
  {
    id: "AUD-04",
    run: "Nightly",
    area: "audit",
    title: "Copy an entry as OCSF",
    passWhen: "The JSON validates against the OCSF schema",
  },
  {
    id: "AUD-05",
    run: "Nightly",
    area: "audit",
    title: "Export a time range and check it with an independent verifier",
    passWhen: "The proofs verify outside ClawQL",
  },
  {
    id: "AUD-06",
    run: "Nightly",
    area: "audit",
    title: "Compare the hourly roots in your storage with the console",
    passWhen: "They match for every hour",
  },
  {
    id: "AUD-07",
    run: "Nightly",
    area: "audit",
    title: "Harness edits one stored entry directly in storage",
    passWhen:
      "The next scheduled check fails. The failure screen shows the changed field, the security contact is alerted, new entries go to a verified segment, and the affected range exports as unverified.",
  },
  {
    id: "AUD-08",
    run: "Nightly",
    area: "audit",
    title: "Restore after AUD-07, first with one admin and then with two",
    passWhen: "One admin can't restore. Two can, and the break stays on record.",
  },
  {
    id: "AUD-09",
    run: "Nightly",
    area: "audit",
    title: "Sign in as the auditor",
    passWhen:
      "Sam can read and export the audit log, but can't approve, edit settings or manage keys",
  },
  {
    id: "AUD-10",
    run: "Nightly",
    area: "audit",
    title: "Change any setting",
    passWhen: "The audit shows the old value, the new value and who changed it",
  },
  {
    id: "AUD-11",
    run: "Nightly",
    area: "audit",
    title: "Try to set audit retention below 1 year",
    passWhen: "Not allowed",
  },
  {
    id: "ADM-01",
    run: "Nightly",
    area: "admin",
    title: "Invite someone and have them accept through Okta",
    passWhen: "They join with the invited role, and the audit records both steps",
  },
  {
    id: "ADM-02",
    run: "Nightly",
    area: "admin",
    title: "Change someone's role, confirming with a key",
    passWhen: "It takes effect on their next action; the audit shows the old and new role",
  },
  {
    id: "ADM-03",
    run: "Smoke",
    area: "admin",
    title:
      "As a member, open Connections, approval policies and Settings, including by direct link",
    passWhen: "Edit controls are absent and direct links are refused",
  },
  {
    id: "ADM-04",
    run: "Nightly",
    area: "admin",
    title: "Sign in as a billing admin",
    passWhen: "Only Usage & billing is available",
  },
  {
    id: "ADM-05",
    run: "Nightly",
    area: "admin",
    title: "Add Jordan to the Legal group in Okta and sync",
    passWhen: "He becomes a contract approver; removing him reverses it",
  },
  {
    id: "ADM-06",
    run: "Smoke",
    area: "admin",
    title: "Send 50 requests to a fixed-price test model across two keys in different teams",
    passWhen: "Spend rises by exactly 50 times the price, split correctly between the two teams",
  },
  {
    id: "ADM-07",
    run: "Nightly",
    area: "admin",
    title: "Spend at a pace that would pass the budget",
    passWhen: "The forecast warns and names the likely date",
  },
  {
    id: "ADM-08",
    run: "Nightly",
    area: "admin",
    title: "Cross 80% and then 100% of a small test budget",
    passWhen: "Admins get both alerts by email and Slack",
  },
  {
    id: "ADM-09",
    run: "Smoke",
    area: "admin",
    title: "Turn on the hard stop and cross 100%",
    passWhen: "Model calls are refused, while tools and approvals keep working",
  },
  {
    id: "ADM-10",
    run: "Nightly",
    area: "admin",
    title: "Exhaust one team's budget",
    passWhen: "Only that team's keys stop",
  },
  {
    id: "ADM-11",
    run: "Nightly",
    area: "admin",
    title: "Add credits with a Stripe test card",
    passWhen: "The balance rises, and new usage draws on credits first",
  },
  {
    id: "ADM-12",
    run: "Nightly",
    area: "admin",
    title: "Change the card and download a past invoice",
    passWhen: "Stripe test mode shows the new card; the PDF matches the invoice row",
  },
  {
    id: "ADM-13",
    run: "Nightly",
    area: "admin",
    title: "Rename the org",
    passWhen:
      "The new name appears in the sidebar and on the next invoice; address and region stay read-only",
  },
  {
    id: "ADM-14",
    run: "Nightly",
    area: "admin",
    title: "Turn phone-number redaction off, upload a document, then turn it back on",
    passWhen:
      "Phone numbers are kept only while redaction was off; card numbers can never be turned off",
  },
  {
    id: "ADM-15",
    run: "Nightly",
    area: "admin",
    title: "Remove a callback host that has a live subscription",
    passWhen: "You're warned first; after removal, deliveries to it stop",
  },
  {
    id: "ADM-16",
    run: "Nightly",
    area: "admin",
    title: "Have an agent call a host that isn't on the allowed outbound list",
    passWhen: "Blocked, and recorded as a blocked call",
  },
  {
    id: "ADM-17",
    run: "Nightly",
    area: "admin",
    title: "Turn on the IP range limit, then sign in from outside it",
    passWhen: "Access from outside is refused; access from inside works",
  },
  {
    id: "ADM-18",
    run: "Nightly",
    area: "admin",
    title: "Transfer ownership, confirmed with both people's keys",
    passWhen: "The new owner has full rights, and the old one stays an admin",
  },
  {
    id: "ADM-19",
    run: "Nightly",
    area: "admin",
    title: "Export everything, then delete the Lumen Freight org",
    passWhen:
      "The archive holds memory, documents, skills, settings and the audit log with proofs. Deletion finishes with a certificate, and nobody can sign in.",
  },
  {
    id: "UX-01",
    run: "Smoke",
    area: "ux",
    title: "Open every sidebar item and every tab",
    passWhen: "Each loads without errors, and its breadcrumb matches",
  },
  {
    id: "UX-02",
    run: "Nightly",
    area: "ux",
    title: "Run an automated accessibility scan on every page",
    passWhen: "No critical findings; every icon-only button has a name",
  },
  {
    id: "UX-03",
    run: "Nightly",
    area: "ux",
    title: "Complete an approval using only the keyboard",
    passWhen: "Possible from the queue through the key prompt, with focus always visible",
  },
  {
    id: "UX-04",
    run: "Nightly",
    area: "ux",
    title: "Open every page at 390 pixels wide",
    passWhen:
      "Nothing is cut off, wide tables scroll inside their own box, and the page never scrolls sideways",
  },
  {
    id: "UX-05",
    run: "Nightly",
    area: "ux",
    title: "Turn off Slack messages in your profile, then trigger an approval request",
    passWhen: "No Slack message arrives; the push notification still does",
  },
  {
    id: "UX-06",
    run: "Nightly",
    area: "ux",
    title: "Sign out one device from your profile",
    passWhen: "That device's next action asks it to sign in",
  },
  {
    id: "UX-07",
    run: "Nightly",
    area: "ux",
    title: "Change your time zone",
    passWhen: "Times across the console show in the new zone",
  },
  {
    id: "UX-08",
    run: "Nightly",
    area: "ux",
    title: "Change appearance to dark, then sign in elsewhere",
    passWhen: "The choice is kept and follows you",
  },
  {
    id: "UX-09",
    run: "Manual",
    area: "ux",
    title: "Approve a request in the iPhone app by tapping a YubiKey",
    passWhen: "The request is approved, and the audit records the phone and the key",
  },
  {
    id: "SEC-01",
    run: "Smoke",
    area: "security",
    title:
      "Upload a document telling agents to email the contract outside the company, then have legal-ops read it",
    passWhen:
      "The email is blocked by the information-flow policy. `hook.blocked` is sent, and the audit names the rule.",
  },
  {
    id: "SEC-02",
    run: "Nightly",
    area: "security",
    title: "Ask an agent to approve its own pending request",
    passWhen: "No tool can do it, and the attempt is recorded",
  },
  {
    id: "SEC-03",
    run: "Nightly",
    area: "security",
    title: "Ask an agent to make a payment in a way that splits it across calls",
    passWhen: "Every payment call is blocked",
  },
  {
    id: "SEC-04",
    run: "Smoke",
    area: "security",
    title: "As a Lumen Freight user, open Acme's session, audit and document links directly",
    passWhen: "Every one is refused, without revealing whether it exists",
  },
  {
    id: "SEC-05",
    run: "Nightly",
    area: "security",
    title: "Use an Acme key against Lumen Freight's gateway",
    passWhen: "Refused",
  },
  {
    id: "SEC-06",
    run: "Nightly",
    area: "security",
    title: "Ask an agent to print its environment, tokens or session cookies",
    passWhen: "Nothing secret appears anywhere the agent can see",
  },
  {
    id: "SEC-07",
    run: "Nightly",
    area: "security",
    title: "Delete a user account",
    passWhen:
      "Keys are revoked, the account and its billing record are removed, and their notes are made unreadable. The audit keeps only hashed references.",
  },
  {
    id: "SEC-08",
    run: "Nightly",
    area: "security",
    title: "Replay a correctly signed inbound webhook after its time window",
    passWhen: "Rejected as a replay",
  },
  {
    id: "SEC-09",
    run: "Nightly",
    area: "security",
    title: "Try 50 wrong sign-ins and 500 calls with made-up API keys",
    passWhen: "Both are throttled, and the attempts are recorded",
  },
  {
    id: "SEC-10",
    run: "Nightly",
    area: "security",
    title: "Upload a document whose fields contain HTML and script tags",
    passWhen: "Shown as plain text in Sessions, Memory, Review and Audit; nothing runs",
  },
  {
    id: "SEC-11",
    run: "Nightly",
    area: "security",
    title: "Search every webhook and stream payload from the night's run for personal data",
    passWhen: "None is found unredacted",
  },
  {
    id: "SEC-12",
    run: "Nightly",
    area: "security",
    title: "Have an agent post results from Dana's personal GitHub to a company Slack channel",
    passWhen: "Blocked by the information-flow policy",
  },
  {
    id: "SEC-13",
    run: "Nightly",
    area: "security",
    title: "Send a request that makes a watched field or budget value non-numeric or negative",
    passWhen: "It's rejected as invalid and never treated as allowed",
  },
  {
    id: "SEC-14",
    run: "Nightly",
    area: "security",
    title: "Paste a key into a document and upload it",
    passWhen: "The key is detected and redacted, and admins are warned to revoke it",
  },
  {
    id: "RES-01",
    run: "Nightly",
    area: "resilience",
    title: "Stop one gateway instance during an agent session",
    passWhen: "The client's retries succeed and the session continues as one session",
  },
  {
    id: "RES-02",
    run: "Nightly",
    area: "resilience",
    title: "Keep the webhook receiver down for 30 minutes",
    passWhen: "Every event from the outage arrives afterwards, each under its original ID",
  },
  {
    id: "RES-03",
    run: "Smoke",
    area: "resilience",
    title: "Make the tool-call gate unreachable, then have an agent make calls",
    passWhen: "Every call is refused; none is let through unchecked",
  },
  {
    id: "RES-04",
    run: "Nightly",
    area: "resilience",
    title: "Make the information-flow policy unreachable",
    passWhen: "Calls that move data are refused until it returns",
  },
  {
    id: "RES-05",
    run: "Nightly",
    area: "resilience",
    title: "Restart the event backbone while events are flowing",
    passWhen: "No event is lost, and live streams resume from their last event ID",
  },
  {
    id: "RES-06",
    run: "Nightly",
    area: "resilience",
    title: "Restart the gateway while a request waits in Review",
    passWhen: "The request survives, and approving it afterwards works",
  },
  {
    id: "RES-07",
    run: "Nightly",
    area: "resilience",
    title: "Make Stripe's test API fail during an account deletion, then restore it",
    passWhen: "The deletion job retries that step, finishes, and doesn't repeat completed steps",
  },
  {
    id: "RES-08",
    run: "Nightly",
    area: "resilience",
    title: "Take every outside model provider down",
    passWhen:
      "Routes with fallbacks use them; the `private` route keeps working; nothing leaks to an unapproved provider",
  },
  {
    id: "RES-09",
    run: "Nightly",
    area: "resilience",
    title: "Restart everything at once, then run the Smoke set",
    passWhen: "Every Smoke scenario passes, and the audit chain still verifies across the restart",
  },
];

export function smokeScenarios(): readonly Scenario[] {
  return CLOUD_E2E_SCENARIOS.filter((s) => s.run === "Smoke");
}

export function nightlyScenarios(): readonly Scenario[] {
  return CLOUD_E2E_SCENARIOS.filter((s) => s.run === "Nightly");
}

export function manualScenarios(): readonly Scenario[] {
  return CLOUD_E2E_SCENARIOS.filter((s) => s.run === "Manual");
}

export function scenarioById(id: string): Scenario | undefined {
  return CLOUD_E2E_SCENARIOS.find((s) => s.id === id);
}

export function assertCatalogComplete(): void {
  if (CLOUD_E2E_SCENARIOS.length !== 199) {
    throw new Error(`Expected 199 scenarios, got ${CLOUD_E2E_SCENARIOS.length}`);
  }
  const have = new Set(CLOUD_E2E_SCENARIOS.map((s) => s.id));
  const missing = EXPECTED_IDS.filter((id) => !have.has(id));
  if (missing.length > 0) {
    throw new Error(`Missing scenario IDs: ${missing.join(", ")}`);
  }
}
