apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment-graphql.yaml
  - service-graphql.yaml
  - deployment-mcp-http.yaml
  - service-mcp-http.yaml

images:
  - name: clawql-mcp
    newName: clawql-mcp
    newTag: latest
