/**
 * Generate read-only MCP tool definitions from ontology Entity actions.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { defaultOntologySearchRoots, loadOntologyEntities } from "./load.js";
import type {
  GeneratedReadTool,
  OntologyGenerateResult,
  OntologyLintResult,
  OntologyRelationship,
} from "./types.js";
import { lintOntology } from "./lint.js";

function snakeEntity(name: string): string {
  return name
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/\s+/g, "_")
    .toLowerCase();
}

function relationshipToolName(fromEntity: string, rel: OntologyRelationship): string {
  const snake = snakeEntity(fromEntity);
  if (rel.via?.startsWith(snake)) return `get_${rel.via}`;
  return `get_${snake}_${snakeEntity(rel.entity)}s`;
}

function defaultReadToolsForEntity(
  entityName: string
): Omit<GeneratedReadTool, "sourcePath" | "entity">[] {
  const snake = snakeEntity(entityName);
  return [
    {
      name: `search_${snake}s`,
      kind: "read",
      description: `Search ${entityName} entities by free-text query`,
      inputSchema: {
        query: { type: "string", description: "Search query" },
        limit: { type: "number", description: "Max results", optional: true },
      },
    },
    {
      name: `get_${snake}`,
      kind: "read",
      description: `Fetch a single ${entityName} by id`,
      inputSchema: {
        id: { type: "string", description: `${entityName} identifier` },
      },
    },
  ];
}

function relationshipToolsForEntity(
  entityName: string,
  relationships: OntologyRelationship[] | undefined,
  sourcePath: string
): GeneratedReadTool[] {
  const out: GeneratedReadTool[] = [];
  for (const rel of relationships ?? []) {
    out.push({
      name: relationshipToolName(entityName, rel),
      entity: entityName,
      kind: "read",
      description:
        rel.description?.trim() ||
        `Traverse ${entityName} → ${rel.entity} (${rel.type}${rel.via ? ` via ${rel.via}` : ""})`,
      inputSchema: {
        id: { type: "string", description: `${entityName} identifier` },
      },
      sourcePath,
    });
  }
  return out;
}

export type GenerateOntologyOptions = {
  rootDir?: string;
  paths?: string[];
  schemaPath?: string;
  /** Output directory for tools.json + plugin stub. */
  outDir: string;
  /** Skip lint gate (not recommended). */
  skipLint?: boolean;
  /** When true, synthesize search_/get_ tools if entity has no read actions. */
  synthesizeDefaults?: boolean;
};

function renderOkfIndex(entities: LoadedMeta[]): string {
  const lines = [
    "---",
    'type: "index"',
    'title: "Ontology entity catalog"',
    'description: "OKF catalog of enterprise Ontology entity types (Git schema)"',
    'tags: ["ontology", "okf", "index"]',
    `timestamp: "${new Date().toISOString()}"`,
    "clawql_okf: true",
    "---",
    "",
    "# Ontology entity catalog",
    "",
    "Generated by `clawql ontology generate`. Prefer this index before loading full `.cqe` bodies.",
    "",
  ];
  for (const e of entities) {
    lines.push(`- **${e.name}** — ${e.description} (\`${e.relPath}\`)`);
  }
  lines.push("");
  return lines.join("\n");
}

type LoadedMeta = {
  name: string;
  description: string;
  relPath: string;
  pii: string[];
  sources: unknown[];
};

function renderOnyxStubs(entities: LoadedMeta[]): string {
  return `${JSON.stringify(
    {
      apiVersion: "clawql.dev/ontology/v1alpha1",
      kind: "OnyxSourceStubs",
      note: "Manual apply — automatic Onyx connector sync is not yet wired (essay gap B5/8.2).",
      entities: entities.map((e) => ({
        name: e.name,
        sources: e.sources,
        pii_fields: e.pii,
      })),
    },
    null,
    2
  )}\n`;
}

export async function generateOntologyReadTools(opts: GenerateOntologyOptions): Promise<{
  result: OntologyGenerateResult;
  lint?: OntologyLintResult;
  written: string[];
}> {
  const rootDir = resolve(opts.rootDir ?? process.cwd());
  const search =
    opts.paths && opts.paths.length > 0
      ? opts.paths.map((p) => resolve(rootDir, p))
      : defaultOntologySearchRoots(rootDir);

  let lint: OntologyLintResult | undefined;
  if (!opts.skipLint) {
    lint = await lintOntology({
      rootDir,
      paths: search,
      schemaPath: opts.schemaPath,
    });
    if (!lint.ok) {
      return {
        result: { tools: [], deferredWriteActions: [], entities: lint.entities },
        lint,
        written: [],
      };
    }
  }

  const { loaded, loadErrors } = await loadOntologyEntities(search);
  if (loadErrors.length) {
    throw new Error(loadErrors.map((e) => `${e.path}: ${e.message}`).join("\n"));
  }

  const tools: GeneratedReadTool[] = [];
  const deferredWriteActions: OntologyGenerateResult["deferredWriteActions"] = [];
  const entities: string[] = [];
  const metas: LoadedMeta[] = [];
  const synthesize = opts.synthesizeDefaults !== false;
  const seenToolNames = new Set<string>();

  const pushTool = (t: GeneratedReadTool) => {
    if (seenToolNames.has(t.name)) return;
    seenToolNames.add(t.name);
    tools.push(t);
  };

  for (const { path, entity } of loaded) {
    const name = entity.metadata?.name;
    if (!name) continue;
    entities.push(name);
    metas.push({
      name,
      description: entity.spec?.description ?? "",
      relPath: path,
      pii: entity.spec?.pii_fields ?? [],
      sources: entity.spec?.sources ?? [],
    });
    const actions = entity.spec?.actions ?? [];
    const readActions = actions.filter((a) => a.kind === "read");
    for (const a of actions.filter((x) => x.kind === "write")) {
      deferredWriteActions.push({ entity: name, name: a.name, sourcePath: path });
    }

    if (readActions.length === 0 && synthesize) {
      for (const t of defaultReadToolsForEntity(name)) {
        pushTool({ ...t, entity: name, sourcePath: path });
      }
    } else {
      for (const a of readActions) {
        pushTool({
          name: a.name,
          entity: name,
          kind: "read",
          description: a.description?.trim() || `Read action ${a.name} on ${name}`,
          inputSchema: {
            query: {
              type: "string",
              description: "Optional query / filter",
              optional: true,
            },
            id: {
              type: "string",
              description: `${name} identifier when fetching one record`,
              optional: true,
            },
          },
          sourcePath: path,
        });
      }
    }

    for (const t of relationshipToolsForEntity(name, entity.spec?.relationships, path)) {
      pushTool(t);
    }
  }

  const result: OntologyGenerateResult = { tools, deferredWriteActions, entities };
  const outDir = resolve(opts.outDir);
  await mkdir(outDir, { recursive: true });

  const toolsJsonPath = join(outDir, "tools.json");
  const catalog = {
    apiVersion: "clawql.dev/ontology/v1alpha1",
    kind: "GeneratedReadTools",
    generatedAt: new Date().toISOString(),
    entities,
    tools,
    deferredWriteActions,
  };
  await writeFile(toolsJsonPath, `${JSON.stringify(catalog, null, 2)}\n`, "utf8");

  const pluginPath = join(outDir, "ontology-plugin.stub.ts");
  await writeFile(pluginPath, renderPluginStub(tools), "utf8");

  const indexPath = join(outDir, "index.md");
  await writeFile(indexPath, renderOkfIndex(metas), "utf8");

  const onyxPath = join(outDir, "onyx-sources.stub.json");
  await writeFile(onyxPath, renderOnyxStubs(metas), "utf8");

  const readmePath = join(outDir, "README.md");
  await writeFile(
    readmePath,
    [
      "# Generated ontology read tools",
      "",
      "Produced by `clawql ontology generate` (ADR 0009).",
      "",
      `- **tools.json** — MCP tool catalog (read-only + relationship traversals)`,
      `- **index.md** — OKF entity catalog (prefer before loading full \`.cqe\` bodies)`,
      `- **onyx-sources.stub.json** — Onyx connector stubs from \`sources:\` (manual apply)`,
      `- **ontology-plugin.stub.ts** — catalog constant; live tools register via \`CLAWQL_ENABLE_ONTOLOGY=1\``,
      "",
      "Write / kinetic actions are listed under `deferredWriteActions` and are **not** registered until Transaction Sandbox ships.",
      "",
    ].join("\n"),
    "utf8"
  );

  return {
    result,
    lint,
    written: [toolsJsonPath, pluginPath, indexPath, onyxPath, readmePath],
  };
}

function renderPluginStub(tools: GeneratedReadTool[]): string {
  const toolList = tools
    .map(
      (t) =>
        `  { name: ${JSON.stringify(t.name)}, entity: ${JSON.stringify(t.entity)}, description: ${JSON.stringify(t.description)} }`
    )
    .join(",\n");

  return `/**
 * AUTO-GENERATED by \`clawql ontology generate\` — do not hand-edit.
 * Read-only MCP tool catalog for the enterprise Ontology (ADR 0009).
 *
 * Live registration: set CLAWQL_ENABLE_ONTOLOGY=1 (fixture-backed handlers in clawql-ontology/plugin).
 */

export const ONTOLOGY_READ_TOOLS = [
${toolList}
] as const;
`;
}

/** @internal exported for tests */
export function _relationshipToolNameForTests(from: string, rel: OntologyRelationship): string {
  return relationshipToolName(from, rel);
}
