import { Effect } from "effect";

import { ObservabilityError } from "../errors.js";
import { LGTM_LOKI_PROVIDER_ID } from "../providers/lgtm-loki.js";
import { LGTM_MIMIR_PROVIDER_ID } from "../providers/lgtm-mimir.js";
import { LGTM_TEMPO_PROVIDER_ID } from "../providers/lgtm-tempo.js";
import { sanitizeRiverComponentNameEffect } from "./sanitize.js";
import type { AlloyGenerationInput, AlloyGeneratedConfig, AlloyProviderEntry } from "./types.js";

const HEADER = `// Generated by clawql-observability Alloy config generator (Phase 3b).
// Registry is source of truth — do not hand-edit generated exporter blocks.
`;

const resolveOtlpEndpoint = (entry: AlloyProviderEntry): string => {
  const otlp = entry.config.otlpEndpoint;
  if (typeof otlp === "string" && otlp.trim() !== "") {
    return otlp.trim();
  }
  if (entry.id === LGTM_LOKI_PROVIDER_ID) {
    const base = (entry.config.endpoint ?? "http://loki:3100").replace(/\/$/, "");
    return `${base}/otlp`;
  }
  if (entry.id === LGTM_TEMPO_PROVIDER_ID) {
    return "http://tempo:4318";
  }
  const endpoint = entry.config.endpoint?.trim();
  if (!endpoint) {
    throw new ObservabilityError({
      reason: `provider ${entry.id} missing endpoint for OTLP exporter`,
    });
  }
  return endpoint.replace(/\/$/, "");
};

const resolveRemoteWriteUrl = (entry: AlloyProviderEntry): string => {
  const pushUrl = entry.config.pushUrl;
  if (typeof pushUrl === "string" && pushUrl.trim() !== "") {
    return pushUrl.trim();
  }
  if (entry.id === LGTM_MIMIR_PROVIDER_ID) {
    const base = (entry.config.endpoint ?? "http://mimir:9009").replace(/\/$/, "");
    return `${base}/api/v1/push`;
  }
  const endpoint = entry.config.endpoint?.trim();
  if (!endpoint) {
    throw new ObservabilityError({
      reason: `provider ${entry.id} missing endpoint for remote_write`,
    });
  }
  return endpoint.replace(/\/$/, "");
};

const resolveLokiPushUrl = (entry: AlloyProviderEntry): string => {
  const pushUrl = entry.config.pushUrl;
  if (typeof pushUrl === "string" && pushUrl.trim() !== "") {
    return pushUrl.trim();
  }
  const base = (entry.config.endpoint ?? "http://loki:3100").replace(/\/$/, "");
  return `${base}/loki/api/v1/push`;
};

const enabled = (entries: readonly AlloyProviderEntry[]): AlloyProviderEntry[] =>
  entries.filter((entry) => entry.enabled && entry.config.enabled !== false);

const renderLogExporter = (
  componentName: string,
  entry: AlloyProviderEntry
): { readonly block: string; readonly batchRef: string } => {
  const otlp = resolveOtlpEndpoint(entry);
  return {
    batchRef: `otelcol.exporter.otlphttp.${componentName}.input`,
    block: `otelcol.exporter.otlphttp "${componentName}" {
  client {
    endpoint = "${otlp}"
  }
}`,
  };
};

const renderTraceExporter = (
  componentName: string,
  entry: AlloyProviderEntry
): { readonly block: string; readonly batchRef: string } => {
  const otlp = resolveOtlpEndpoint(entry);
  return {
    batchRef: `otelcol.exporter.otlphttp.${componentName}.input`,
    block: `otelcol.exporter.otlphttp "${componentName}" {
  client {
    endpoint = "${otlp}"
  }
}`,
  };
};

const renderMetricExporter = (
  componentName: string,
  entry: AlloyProviderEntry
): { readonly blocks: string[]; readonly batchRef: string } => {
  const url = resolveRemoteWriteUrl(entry);
  const tenantId =
    typeof entry.config.tenantId === "string" && entry.config.tenantId.trim() !== ""
      ? entry.config.tenantId.trim()
      : undefined;

  const remoteWriteName = `remote_write_${componentName}`;
  const headers = tenantId
    ? `
    headers = {
      "X-Scope-OrgID" = "${tenantId}",
    }`
    : "";

  return {
    batchRef: `otelcol.exporter.prometheus.${componentName}.input`,
    blocks: [
      `otelcol.exporter.prometheus "${componentName}" {
  forward_to = [prometheus.remote_write.${remoteWriteName}.receiver]
}`,
      `prometheus.remote_write "${remoteWriteName}" {
  endpoint {
    url = "${url}"${headers}
  }
}`,
    ],
  };
};

const formatList = (refs: readonly string[]): string => {
  if (refs.length === 0) {
    return "[]";
  }
  if (refs.length === 1) {
    return `[${refs[0]}]`;
  }
  return `[\n${refs.map((ref) => `      ${ref},`).join("\n")}\n    ]`;
};

/** Generate a complete Alloy River config from registry snapshots. */
export const generateAlloyRiverEffect = (
  input: AlloyGenerationInput
): Effect.Effect<AlloyGeneratedConfig, ObservabilityError> =>
  Effect.gen(function* () {
    const logs = enabled(input.logs);
    const metrics = enabled(input.metrics);
    const traces = enabled(input.traces);

    if (logs.length === 0 && metrics.length === 0 && traces.length === 0) {
      return yield* Effect.fail(
        new ObservabilityError({
          reason: "Alloy generation requires at least one enabled log, metric, or trace provider",
        })
      );
    }

    const exporterBlocks: string[] = [];
    const logRefs: string[] = [];
    const metricRefs: string[] = [];
    const traceRefs: string[] = [];
    const providerIds: string[] = [];

    for (const entry of logs) {
      const name = yield* sanitizeRiverComponentNameEffect(entry.id);
      const rendered = renderLogExporter(name, entry);
      exporterBlocks.push(rendered.block);
      logRefs.push(rendered.batchRef);
      providerIds.push(entry.id);
    }

    for (const entry of metrics) {
      const name = yield* sanitizeRiverComponentNameEffect(entry.id);
      const rendered = renderMetricExporter(name, entry);
      exporterBlocks.push(...rendered.blocks);
      metricRefs.push(rendered.batchRef);
      providerIds.push(entry.id);
    }

    for (const entry of traces) {
      const name = yield* sanitizeRiverComponentNameEffect(entry.id);
      const rendered = renderTraceExporter(name, entry);
      exporterBlocks.push(rendered.block);
      traceRefs.push(rendered.batchRef);
      providerIds.push(entry.id);
    }

    const includeFaro = input.includeFaro ?? logs.length > 0;
    const faroPort = input.faroPort ?? 8027;
    const primaryLog = logs[0];
    const faroBlocks: string[] = [];

    if (includeFaro && primaryLog) {
      const faroName = yield* sanitizeRiverComponentNameEffect(primaryLog.id);
      const pushUrl = resolveLokiPushUrl(primaryLog);
      faroBlocks.push(`// Faro browser ingest (Worker proxy forwards here privately).
faro.receiver "frontend" {
  server {
    listen_address       = "0.0.0.0"
    listen_port          = ${faroPort}
    cors_allowed_origins = ["*"]
  }

  output {
    logs   = [loki.write.faro_${faroName}.receiver]
    traces = [otelcol.processor.batch.default.input]
  }
}

loki.write "faro_${faroName}" {
  endpoint {
    url = "${pushUrl}"
  }
}`);
    }

    const river = [
      HEADER.trimEnd(),
      "",
      `logging {
  level = "info"
}`,
      "",
      `otelcol.receiver.otlp "default" {
  grpc {
    endpoint = "0.0.0.0:4317"
  }

  http {
    endpoint = "0.0.0.0:4318"
  }

  output {
    metrics = [otelcol.processor.batch.default.input]
    logs    = [otelcol.processor.batch.default.input]
    traces  = [otelcol.processor.batch.default.input]
  }
}`,
      "",
      `otelcol.processor.batch "default" {
  timeout         = "5s"
  send_batch_size = 1000

  output {
    metrics = ${formatList(metricRefs)}
    logs    = ${formatList(logRefs)}
    traces  = ${formatList(traceRefs)}
  }
}`,
      "",
      ...exporterBlocks,
      "",
      ...faroBlocks,
      "",
    ]
      .join("\n")
      .replace(/\n{3,}/g, "\n\n")
      .trimEnd()
      .concat("\n");

    return {
      river,
      exporterRefs: {
        logs: logRefs,
        metrics: metricRefs,
        traces: traceRefs,
      },
      providerIds,
    };
  });

/** Thin host façade for scripts. */
export const generateAlloyRiver = (input: AlloyGenerationInput): AlloyGeneratedConfig =>
  Effect.runSync(generateAlloyRiverEffect(input));
