#!/usr/bin/env bash
# Tier 1 local bootstrap — prerequisites, secrets, clawql.local.yaml ([#251](https://github.com/danielsmithdevelopment/ClawQL/issues/251)).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${ROOT}"

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "ERROR: required command not found: $1" >&2
    exit 1
  fi
}

require_cmd docker
if ! docker compose version >/dev/null 2>&1; then
  echo "ERROR: Docker Compose v2 is required (docker compose)." >&2
  exit 1
fi

check_port() {
  local port="$1"
  if command -v ss >/dev/null 2>&1; then
    if ss -ltn | awk '{print $4}' | grep -qE ":${port}$"; then
      echo "ERROR: port ${port} is already in use." >&2
      exit 1
    fi
  fi
}

for port in 8080 5432 6379; do
  check_port "${port}"
done

mkdir -p data/vault secrets

if [[ ! -f secrets/paperless.key ]]; then
  openssl rand -hex 24 >secrets/paperless.key
fi

PAPERLESS_SECRET_KEY="$(openssl rand -hex 32)"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-paperless}"
PAPERLESS_ADMIN_PASSWORD="${PAPERLESS_ADMIN_PASSWORD:-$(openssl rand -hex 12)}"

cat >.env <<EOF
# Generated by bootstrap.sh — safe to regenerate (re-run bootstrap).
CLAWQL_VAULT_HOST_PATH=./data/vault
CLAWQL_API_PORT=8080
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
PAPERLESS_SECRET_KEY=${PAPERLESS_SECRET_KEY}
PAPERLESS_ADMIN_USER=admin
PAPERLESS_ADMIN_PASSWORD=${PAPERLESS_ADMIN_PASSWORD}
PAPERLESS_ADMIN_MAIL=admin@localhost
CLAWQL_AUTH_MODE=noAuth
EOF

cat >clawql.local.yaml <<EOF
# clawql.local.yaml — Tier 1 local configuration (generated by bootstrap.sh)
tier: local

api:
  port: 8080
  logLevel: info
  auth:
    mode: noAuth

memory:
  backend: sqlite
  path: ./data/memory.db
  recall:
    defaultMode: hybrid
    maxHops: 3
    maxNodes: 100
    tokenBudget: 16000

documents:
  tika:
    url: http://tika:9998
    timeoutSeconds: 30
  gotenberg:
    url: http://gotenberg:3000
    timeoutSeconds: 60
  paperless:
    url: http://paperless-ngx:8000
    apiKeyRef: local-paperless-key
  presidio:
    enabled: false
    failurePolicy: block

pageindex:
  enabled: true
  storageBackend: file
  path: ./data/pageindex.db.json

telemetry:
  enabled: false

verticals: {}
EOF

echo "Tier 1 bootstrap complete."
echo "  Vault:      ${ROOT}/data/vault"
echo "  Config:     ${ROOT}/clawql.local.yaml"
echo "  Env:        ${ROOT}/.env"
echo "  Paperless:  admin / ${PAPERLESS_ADMIN_PASSWORD}"
echo ""
echo "Next: docker compose up -d"
echo "Verify: curl -fsS http://localhost:8080/healthz"
