/**
 * Generate a thin zero-dependency CLI that calls adapter REST tool endpoints.
 * (PrintingPress can replace/upgrade this later for signed binaries + richer codegen.)
 */

import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { ListedMcpTool } from "mcp-grpc-transport";

export type GenCliOptions = {
  /** Output directory (created if missing). */
  outDir: string;
  /** npm package / binary name (default `mcp-tools`). */
  name?: string;
  /** Default base URL for the running adapter (default `http://127.0.0.1:8090`). */
  baseUrl?: string;
  tools: ListedMcpTool[];
  /** Human label for README (upstream). */
  upstreamLabel?: string;
};

function safeBinName(name: string): string {
  const n = name.trim().toLowerCase().replace(/[^a-z0-9._-]+/g, "-");
  return n || "mcp-tools";
}

function toolArgHelp(tool: ListedMcpTool): string {
  const props = (tool.inputSchema.properties ?? {}) as Record<string, { type?: string }>;
  const keys = Object.keys(props);
  if (keys.length === 0) return "  (no args — or pass JSON via --args '{…}')";
  return keys.map((k) => `  --${k} <value>`).join("\n");
}

/** Render the generated CLI entrypoint source. */
export function renderGeneratedCliSource(options: {
  name: string;
  baseUrl: string;
  tools: ListedMcpTool[];
}): string {
  const toolNames = options.tools.map((t) => t.name);
  const toolsJson = JSON.stringify(
    options.tools.map((t) => ({
      name: t.name,
      description: t.description ?? "",
      inputSchema: t.inputSchema,
    })),
    null,
    2
  );

  return `#!/usr/bin/env node
/**
 * Generated by mcp-api-adapter gen-cli — thin REST client for MCP tools.
 * Upgrade path: clawql-printingpress (signed binaries / richer codegen) when available.
 */
import { parseArgs } from "node:util";

const DEFAULT_BASE = ${JSON.stringify(options.baseUrl)};
const TOOLS = ${toolsJson};

function printHelp() {
  console.log(\`${options.name} — generated MCP tool CLI (via mcp-api-adapter)

Usage:
  ${options.name} <tool> [--key value…] [--args '{json}']
  ${options.name} list
  ${options.name} --help

Env:
  MCP_API_ADAPTER_BASE_URL   Adapter base URL (default \${DEFAULT_BASE})
  MCP_API_ADAPTER_API_KEY    Optional X-API-Key / Bearer token

Tools:
\${TOOLS.map((t) => "  " + t.name + (t.description ? " — " + t.description : "")).join("\\n")}
\`);
}

function parseToolArgs(toolName, tokens) {
  const tool = TOOLS.find((t) => t.name === toolName);
  if (!tool) throw new Error("unknown tool: " + toolName);
  const { values, positionals } = parseArgs({
    args: tokens,
    options: {
      args: { type: "string" },
      help: { type: "boolean", short: "h", default: false },
      "base-url": { type: "string" },
      "api-key": { type: "string" },
    },
    allowPositionals: true,
    strict: false,
  });
  if (values.help) {
    console.log(toolName + "\\n" + (tool.description || "") + "\\n");
    const props = tool.inputSchema?.properties || {};
    for (const k of Object.keys(props)) console.log("  --" + k + " <value>");
    console.log("  --args '{…}'   raw JSON object (overrides flags)");
    process.exit(0);
  }
  let body = {};
  if (values.args) {
    body = JSON.parse(String(values.args));
  } else {
    const props = tool.inputSchema?.properties || {};
    const required = Array.isArray(tool.inputSchema?.required) ? tool.inputSchema.required : [];
    // Collect --key value pairs from remaining argv-style tokens in positionals + unknown
    for (let i = 0; i < tokens.length; i++) {
      const tok = tokens[i];
      if (!tok.startsWith("--") || tok === "--args" || tok === "--base-url" || tok === "--api-key" || tok === "--help" || tok === "-h") continue;
      const key = tok.slice(2);
      if (!(key in props) && !required.includes(key)) {
        // still allow unknown flags as string args
      }
      const next = tokens[i + 1];
      if (next != null && !next.startsWith("--")) {
        const prop = props[key];
        let val = next;
        if (prop?.type === "number" || prop?.type === "integer") val = Number(next);
        else if (prop?.type === "boolean") val = next === "true" || next === "1";
        else {
          try { val = JSON.parse(next); } catch { /* string */ }
        }
        body[key] = val;
        i++;
      } else {
        body[key] = true;
      }
    }
  }
  return {
    body,
    baseUrl: values["base-url"] || process.env.MCP_API_ADAPTER_BASE_URL || DEFAULT_BASE,
    apiKey: values["api-key"] || process.env.MCP_API_ADAPTER_API_KEY || undefined,
  };
}

async function main(argv) {
  if (argv.length === 0 || argv[0] === "--help" || argv[0] === "-h") {
    printHelp();
    return;
  }
  if (argv[0] === "list") {
    for (const t of TOOLS) console.log(t.name + (t.description ? "\\t" + t.description : ""));
    return;
  }
  const toolName = argv[0];
  if (!TOOLS.some((t) => t.name === toolName)) {
    console.error("unknown tool:", toolName);
    printHelp();
    process.exit(1);
  }
  const { body, baseUrl, apiKey } = parseToolArgs(toolName, argv.slice(1));
  const headers = { "content-type": "application/json" };
  if (apiKey) {
    headers["x-api-key"] = apiKey;
    headers["authorization"] = "Bearer " + apiKey;
  }
  const res = await fetch(String(baseUrl).replace(/\\/$/, "") + "/" + toolName, {
    method: "POST",
    headers,
    body: JSON.stringify(body),
  });
  const text = await res.text();
  let out;
  try { out = JSON.parse(text); } catch { out = text; }
  if (!res.ok) {
    console.error(typeof out === "string" ? out : JSON.stringify(out, null, 2));
    process.exit(1);
  }
  console.log(typeof out === "string" ? out : JSON.stringify(out, null, 2));
}

main(process.argv.slice(2)).catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
`;
}

export async function generateToolCli(options: GenCliOptions): Promise<{
  outDir: string;
  binName: string;
  files: string[];
}> {
  const binName = safeBinName(options.name ?? "mcp-tools");
  const baseUrl = (options.baseUrl?.trim() || "http://127.0.0.1:8090").replace(/\/$/, "");
  const outDir = options.outDir;
  await mkdir(outDir, { recursive: true });
  await mkdir(join(outDir, "bin"), { recursive: true });

  const files: string[] = [];

  const pkg = {
    name: binName,
    version: "0.0.0",
    private: true,
    type: "module",
    bin: { [binName]: `bin/${binName}.mjs` },
    engines: { node: ">=22" },
    description: `Generated MCP tool CLI for ${options.upstreamLabel ?? "mcp-api-adapter"} (mcp-api-adapter gen-cli)`,
  };
  await writeFile(join(outDir, "package.json"), JSON.stringify(pkg, null, 2) + "\n");
  files.push("package.json");

  const cliSrc = renderGeneratedCliSource({
    name: binName,
    baseUrl,
    tools: options.tools,
  });
  const binPath = join(outDir, "bin", `${binName}.mjs`);
  await writeFile(binPath, cliSrc, { mode: 0o755 });
  files.push(`bin/${binName}.mjs`);

  const readme = `# ${binName}

Generated by **mcp-api-adapter gen-cli** — thin CLI over the adapter’s REST API (\`POST /{toolName}\`).

Upstream: ${options.upstreamLabel ?? "(unknown)"}  
Default base URL: \`${baseUrl}\`

\`\`\`bash
node bin/${binName}.mjs list
node bin/${binName}.mjs <tool> --flag value
MCP_API_ADAPTER_BASE_URL=${baseUrl} node bin/${binName}.mjs <tool> --args '{"…":…}'
\`\`\`

## Tools

${options.tools.map((t) => `### \`${t.name}\`\n\n${t.description ?? ""}\n\n\`\`\`\n${toolArgHelp(t)}\n\`\`\`\n`).join("\n")}

## PrintingPress

This is a lightweight scaffold. When **clawql-printingpress** ships, prefer it for signed binaries and richer codegen — same tool catalog, production packaging.
`;
  await writeFile(join(outDir, "README.md"), readme);
  files.push("README.md");

  return { outDir, binName, files };
}
