import { Effect } from "effect";
import { escapeMcpUiHtml } from "./mcp-ui-form.js";
import type { GeneratedUiDefinition } from "./mcp-ui-generate.js";

/** Inline styles shared with mcp-ui catalog (kept local so this landing stays self-contained). */
const STYLES = `
:root {
  --bg: #0f1419;
  --surface: #1a222c;
  --ink: #e7eef7;
  --muted: #9aa8b8;
  --accent: #3dd6c6;
  --line: #2a3542;
}
* { box-sizing: border-box; }
body {
  margin: 0;
  font-family: "IBM Plex Sans", "Segoe UI", sans-serif;
  background:
    radial-gradient(1200px 600px at 10% -10%, #1b3a3a 0%, transparent 55%),
    radial-gradient(900px 500px at 100% 0%, #24304a 0%, transparent 50%),
    var(--bg);
  color: var(--ink);
  min-height: 100vh;
}
.page { max-width: 52rem; margin: 0 auto; padding: 2rem 1.25rem 3rem; }
.hero h1 { font-size: 1.75rem; margin: 0 0 0.5rem; letter-spacing: -0.02em; }
.hero p { color: var(--muted); line-height: 1.55; margin: 0 0 1rem; }
.badge {
  display: inline-block;
  font-size: 0.7rem;
  letter-spacing: 0.12em;
  text-transform: uppercase;
  color: var(--accent);
  margin-bottom: 0.75rem;
}
.card {
  background: var(--surface);
  border: 1px solid var(--line);
  border-radius: 12px;
  padding: 1.1rem 1.2rem;
  margin: 1rem 0;
}
.card h2 { margin: 0 0 0.5rem; font-size: 1.05rem; }
.steps { list-style: none; padding: 0; margin: 0.75rem 0 0; }
.steps li {
  padding: 0.45rem 0;
  border-top: 1px solid var(--line);
  font-size: 0.92rem;
}
.steps code { color: var(--accent); font-size: 0.85em; }
.actions { display: flex; flex-wrap: wrap; gap: 0.75rem; margin-top: 1.25rem; }
.btn {
  display: inline-block;
  background: var(--accent);
  color: #06241f;
  font-weight: 650;
  text-decoration: none;
  border: none;
  border-radius: 8px;
  padding: 0.65rem 1rem;
  cursor: pointer;
  font-size: 0.95rem;
}
.btn--ghost {
  background: transparent;
  color: var(--ink);
  border: 1px solid var(--line);
}
.note { font-size: 0.85rem; color: var(--muted); margin-top: 1rem; line-height: 1.45; }
a { color: var(--accent); }
`;

export type AgentLabLandingOpts = {
  basePath: string;
  title: string;
  definition: GeneratedUiDefinition;
  error?: string;
};

export const renderAgentLabLandingPage = (
  opts: AgentLabLandingOpts
): Effect.Effect<string> =>
  Effect.sync(() => {
    const base = opts.basePath.replace(/\/$/, "") || "/mcp-ui";
    const steps = opts.definition.steps
      .map(
        (s, i) =>
          `<li><strong>Step ${i + 1}.</strong> ${escapeMcpUiHtml(s.label ?? s.tool)} — <code>${escapeMcpUiHtml(s.tool)}</code></li>`
      )
      .join("");
    const err = opts.error
      ? `<div class="card" role="alert"><p>${escapeMcpUiHtml(opts.error)}</p></div>`
      : "";
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${escapeMcpUiHtml(opts.definition.title)} — MCP UI preset</title>
  <style>${STYLES}</style>
</head>
<body>
  <div class="page">
    <header class="hero">
      <div class="badge">Act 2 · /mcp-ui preset</div>
      <h1>${escapeMcpUiHtml(opts.definition.title)}</h1>
      <p>${escapeMcpUiHtml(
        opts.definition.description ??
          "Dynamically scaffolded HTMX workflow — not a static docs page."
      )}</p>
    </header>
    ${err}
    <section class="card">
      <h2>Why this page is not on the docs site</h2>
      <p style="color:var(--muted);margin:0;line-height:1.5">
        Docs WebMCP tools live in the browser. This view is generated by
        <code>mcp-api-adapter</code> from the live MCP catalog: multi-step HTMX
        forms at <code>${escapeMcpUiHtml(base)}/custom/${escapeMcpUiHtml(
      opts.definition.slug ?? "agent-lab"
    )}</code>.
        Same tools, different surface — Protocol Fabric Act 2.
      </p>
      <ol class="steps">${steps}</ol>
    </section>
    <div class="actions">
      <form method="post" action="${escapeMcpUiHtml(base)}/presets/agent-lab/start">
        <button class="btn" type="submit">Start HTMX workflow</button>
      </form>
      <a class="btn btn--ghost" href="${escapeMcpUiHtml(base)}">← Tool catalog</a>
      <a class="btn btn--ghost" href="${escapeMcpUiHtml(base)}/trace/compare">Flamegraph compare</a>
    </div>
    <p class="note">
      Demo upstream: <code>node examples/mcp-api-adapter/docs-agent-lab-server.mjs</code>
      then open this preset. Act 3: follow the correlation id into
      <code>/mcp-ui/trace/compare</code>.
    </p>
  </div>
</body>
</html>`;
  });

export const runRenderAgentLabLandingPage = (opts: AgentLabLandingOpts): string =>
  Effect.runSync(renderAgentLabLandingPage(opts));
