{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clawql-operator.fullname" . }}
  labels:
    {{- include "clawql-operator.labels" . | nindent 4 }}
{{- end }}
