apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch-mcp-deployment.yaml
  - path: patch-graphql-deployment.yaml
  - path: patch-mcp-service.yaml

images:
  - name: clawql-mcp
    newName: clawql-mcp
    newTag: prod
